### PR TITLE
feat: create loading shimmer for panel 1 and 2

### PR DESCRIPTION
**Pull request by shrivatsabhat**
## Description

-

#### Type of change

-

### Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### Data Results

- none

### Additional Info

- none

### CODE REVIEW

**Comment by rayanfer32** [comment]
Can we change Shimmer loading style  to flashing like before , fade-in is not suiting well

**Review by rayanfer32 — CHANGES_REQUESTED** [review]
Can we have old style of shimmer, flashing one

**Comment by shrivatsabhat** [comment]
> Can we have old style of shimmer, flashing one

let me tryout

**Review by rayanfer32 — APPROVED** [review]
Nice , looks neat

**Pull request merged**
